import {
  AiEngineFixtureIds,
  BookContextDocumentV1Fixture,
  LivingWikiVersionV1Fixture,
  type PublicContextV1,
} from "@bookseasoning/contracts/internal";

import type { ClaimedAiJob } from "../ai-jobs/ai-job.queue.js";

export const evaluatorJob: ClaimedAiJob = {
  schemaVersion: "ai-job.v1",
  jobId: "c0000000-0000-4000-8000-000000000001",
  jobType: "PUBLIC_EVALUATION",
  sessionId: AiEngineFixtureIds.sessionId,
  baseWikiVersion: 1,
  targetThroughSeq: 4,
  taskSchemaVersion: "public-evaluator-output.v1",
  queueMessageId: "1",
  queueReadCount: 1,
  attemptNo: 1,
  maxAttempts: 3,
  leaseExpiresAt: "2026-09-02T04:01:00.000Z",
};

export const evaluatorContext: PublicContextV1 = {
  schemaVersion: "public-context.v1",
  builtAt: "2026-09-02T04:00:00.000Z",
  session: {
    sessionId: evaluatorJob.sessionId,
    roomId: "b6000000-0000-4000-8000-000000000001",
    pinnedPackVersionId: BookContextDocumentV1Fixture.packVersionId,
    phase: "CORE",
    phaseVersion: 2,
    aggregateVersion: 8,
    targetThroughSeq: 4,
    latestMessageSeq: 4,
    startedAt: "2026-09-02T03:30:00.000Z",
    discussionEndsAt: "2026-09-02T04:00:00.000Z",
    extensionPromptedAt: null,
    extensionDecisionDeadlineAt: null,
    closingStartedAt: null,
    closingEndsAt: null,
    endedAt: null,
    extensionCount: 0,
  },
  baseWiki: LivingWikiVersionV1Fixture,
  messages: [
    {
      visibility: "PUBLIC",
      messageId: AiEngineFixtureIds.messageId,
      sessionId: evaluatorJob.sessionId,
      seqNo: 3,
      kind: "PARTICIPANT",
      authorParticipantId: AiEngineFixtureIds.participantId,
      authorProfileName: "참가자",
      body: "질문은 이미 알고 있던 생각의 전제를 드러내는 것 같아요.",
      reply: null,
      confirmedAt: "2026-09-02T03:58:00.000Z",
      redactedAt: null,
    },
    {
      visibility: "PUBLIC",
      messageId: AiEngineFixtureIds.secondMessageId,
      sessionId: evaluatorJob.sessionId,
      seqNo: 4,
      kind: "PARTICIPANT",
      authorParticipantId: AiEngineFixtureIds.participantId,
      authorProfileName: "참가자",
      body: "상대와의 관계 속에서 질문이 새 관점을 만든다고도 볼 수 있어요.",
      reply: null,
      confirmedAt: "2026-09-02T03:59:00.000Z",
      redactedAt: null,
    },
  ],
  publicPrep: [],
  participants: [
    {
      participantId: AiEngineFixtureIds.participantId,
      profileName: "참가자",
      role: "HOST",
      membershipStatus: "PARTICIPATED",
      joinedAt: "2026-09-02T03:00:00.000Z",
      participatedAt: "2026-09-02T03:30:00.000Z",
      connectionStatus: "ONLINE",
      lastSeenAt: "2026-09-02T03:59:30.000Z",
      messageCountThroughCursor: 2,
      lastMessageSeq: 4,
      lastSpokeAt: "2026-09-02T03:59:00.000Z",
    },
  ],
  objectiveMetrics: {
    registeredParticipantCount: 1,
    actualParticipantCount: 1,
    connectedParticipantCount: 1,
    recentSpeakerCount: 1,
    recentSpeakerWindowSeconds: 300,
    lastParticipantMessageAt: "2026-09-02T03:59:00.000Z",
    silenceSeconds: 60,
  },
  recentPolicyAction: null,
  lastCommittedInterventionAt: null,
  bookContext: BookContextDocumentV1Fixture,
};
